In [22]:
import pandas as pd
import numpy as np
import PyPDF2
import os
import csv

In [23]:
def extraer_texto_pdf(nombre_archivo):
    with open(nombre_archivo, 'rb') as archivo_pdf:
        lector_pdf = PyPDF2.PdfReader(archivo_pdf)
        texto = ''
        for pagina in lector_pdf.pages:
            texto += pagina.extract_text()
        return texto

In [24]:
def loac_csv(candidatos,ruta_csv,columns):  
    with open(ruta_csv, 'w', newline='') as archivo_csv:
        writer = csv.writer(archivo_csv)
        
        # Escribir encabezados
        #encabezados = list(participante.keys())
        encabezados = list(columns)
        writer.writerow(encabezados)
        
        # Escribir datos de los candidatos
        writer.writerows(candidatos)

In [25]:
Stack = {
        'Lenguajes': ['Python', 'Java', 'Scala', 'Sas','Bash','Ruby','Html','Css','JavaScrip'],  
        'ETL': ['Apache Airflow', 'Airflow', 'Talend', 'Informatica PowerCenter', 'PowerCenter', 'IBM InfoSphere DataStage', 'DataStage', 'Microsoft SQL Server Integration Services', 'SSIS', 'Oracle Data Integrator', 'ODI'],
        'Cloud': ['Amazon Web Services', 'AWS', 'Microsoft Azure', 'Azure', 'Google Cloud Platform', 'GCP', 'IBM Cloud', 'Oracle Cloud Infrastructure', 'Alibaba Cloud'],
        'Clientes_base_datos': ['SQL','MySQL', 'Oracle Database', 'Microsoft SQL Server', 'PostgreSQL', 'SQLite', 'IBM Db2', 'MariaDB'],
        'Visualizacion': ['Metabase','Tableau', 'Power BI', 'QlikView', 'Plotly', 'Matplotlib', 'Seaborn', 'D3.js', 'Grafana'],
        'Data_Science': ['NumPy', 'Pandas', 'SciPy', 'Scikit-learn', 'TensorFlow', 'Keras', 'PyTorch', 'NLTK'],
        'Big_Data': ['Hadoop', 'Spark', 'Apache Kafka', 'Apache Hive', 'Apache Pig', 'Apache Cassandra', 'Apache HBase', 'Apache Beam'],
        'Almacenes_de_datos': ['Amazon Redshift', 'Snowflake', 'Google BigQuery', 'Microsoft Azure Synapse Analytics', 'Oracle Exadata', 'IBM Db2 Warehouse', 'Teradata']
    }

In [26]:
 # Definir las columnas
columns = ['Nombre', 'Lenguajes', 'ETL', 'Cloud', 'Clientes_base_datos', 'Visualizacion', 'Data_Science', 'Big_Data', 'Almacenes_de_datos']

# Crear un DataFrame vac√≠o con las columnas especificadas
df = pd.DataFrame(columns=columns)

# Ejemplo de uso
path_cv_to_proccesing = "C:/Users/Usuario/Desktop/PP/CV-automatization/1.cv_to_proccesing"

output_file = "C:/Users/Usuario/Desktop/PP/CV-automatization/2.cv_proccesed/data.csv"  

# Crear una lista para almacenar los participantes
dataset = []

In [27]:
# Verificar si la ruta existe
if os.path.exists(path_cv_to_proccesing):
    # Obtener la lista de archivos en la ruta
    archivos = os.listdir(path_cv_to_proccesing)
    candidatos = []
    # Recorrer los archivos y extraer los datos
    for aux_arch in archivos:
        archivo = os.path.join(path_cv_to_proccesing, aux_arch)
        texto_curriculum = extraer_texto_pdf(archivo)
        participante = {
                'Nombre': [],
                'Lenguajes': [],
                'ETL': [],
                'Cloud': [],
                'Clientes_base_datos': [],
                'Visualizacion': [],
                'Data_Science': [],
                'Big_Data': [],
                'Almacenes_de_datos': []
        }
        for categoria, valores in Stack.items():
            for valor in valores:
                if valor.lower() in texto_curriculum.lower():
                    participante[categoria].append(valor)

        longitudes = {categoria: len(valores) for categoria, valores in participante.items()}

        # Encuentra la lista con la mayor longitud
        longitud_maxima = max(longitudes.values())

        #participante['Nombre'] = [aux_arch]

        # Modifica todas las listas para que tengan la longitud de la lista m√°s larga
        for categoria, valores in participante.items():
            if len(valores) < longitud_maxima:
                if categoria == 'Nombre':
                    valores.extend([aux_arch]* (longitud_maxima - len(valores)))
                else:
                    valores.extend([""] * (longitud_maxima - len(valores)))

        # Agregar el participante al dataset
        dataset.append(participante)

        tuplas = list(zip(*participante.values()))

        candidatos.append(tuplas)

    candidatos = [list(candidato) for candidato in candidatos]

    lista_candidatos = []
    for candidato in candidatos:
        for x in candidato:
            lista_candidatos.append(x)
     
    print(lista_candidatos)

    # Crear el DataFrame y guardar como CSV
    loac_csv(lista_candidatos,output_file,columns) 
    print(f"Archivo CSV guardado exitosamente como '{output_file}'")
else:
    print("La ruta especificada no existe.")

[('1651669707651.pdf', 'Java', 'DataStage', '', 'SQL', '', '', '', ''), ('1651669707651.pdf', 'Html', '', '', '', '', '', '', ''), ('1651669707651.pdf', 'Css', '', '', '', '', '', '', ''), ('1651669707651.pdf', 'JavaScrip', '', '', '', '', '', '', ''), ('1658588734591.pdf', '', 'SSIS', '', 'SQL', 'Power BI', '', '', ''), ('1658588734591.pdf', '', 'ODI', '', '', '', '', '', ''), ('1658847017582.pdf', 'Python', '', 'AWS', 'SQL', '', 'Pandas', 'Spark', ''), ('1658847017582.pdf', 'Scala', '', 'GCP', 'MySQL', '', '', '', ''), ('1658847017582.pdf', 'Sas', '', '', '', '', '', '', ''), ('1660228502343.pdf', 'Python', '', 'Amazon Web Services', 'SQL', 'Power BI', 'NumPy', '', ''), ('1660228502343.pdf', '', '', 'AWS', 'MySQL', 'Plotly', 'Pandas', '', ''), ('1660228502343.pdf', '', '', '', '', 'Matplotlib', 'Scikit-learn', '', ''), ('1660228502343.pdf', '', '', '', '', 'Seaborn', '', '', ''), ('1674172158065.pdf', 'Python', 'ODI', 'Amazon Web Services', 'SQL', 'Power BI', 'NumPy', '', ''), ('1674172158065.pdf', '', '', 'AWS', '', 'Plotly', 'Pandas', '', ''), ('1674172158065.pdf', '', '', 'Azure', '', 'Matplotlib', 'Scikit-learn', '', ''), ('1674172158065.pdf', '', '', '', '', 'Seaborn', '', '', ''), ('1683641448404.pdf', 'Python', 'SSIS', '', 'SQL', 'Tableau', '', '', ''), ('1683641448404.pdf', 'Java', '', '', '', 'Power BI', '', '', ''), ('1686055981531.pdf', 'Python', 'ODI', '', 'SQL', '', '', '', ''), ('1686055981531.pdf', 'Java', '', '', 'MySQL', '', '', '', ''), ('1686055981531.pdf', 'Html', '', '', 'PostgreSQL', '', '', '', ''), ('1686055981531.pdf', 'Css', '', '', '', '', '', '', ''), ('1686055981531.pdf', 'JavaScrip', '', '', '', '', '', '', ''), ('1687373526225.pdf', 'Python', '', '', 'SQL', '', '', '', ''), ('1688475392937.pdf', 'Python', '', '', 'SQL', '', '', 'Hadoop', 'Teradata'), ('1688475392937.pdf', 'Scala', '', '', '', '', '', 'Spark', ''), ('1688475392937.pdf', 'Sas', '', '', '', '', '', '', ''), ('1688475392937.pdf', 'Bash', '', '', '', '', '', '', ''), ('1688568455002.pdf', 'Python', '', '', 'SQL', '', 'Pandas', '', ''), ('1688568455002.pdf', 'Sas', '', '', 'Microsoft SQL Server', '', '', '', ''), ('1689046487442.pdf', '', '', '', 'SQL', 'Tableau', '', '', ''), ('1689046487442.pdf', '', '', '', 'MySQL', 'Power BI', '', '', ''), ('Alejandro+Morel+CV+-.pdf', 'Java', '', '', '', '', '', '', ''), ('Alejandro+Morel+CV+-.pdf', 'Sas', '', '', '', '', '', '', ''), ('Alejandro+Morel+CV+-.pdf', 'Html', '', '', '', '', '', '', ''), ('Alejandro+Morel+CV+-.pdf', 'Css', '', '', '', '', '', '', ''), ('Alejandro+Morel+CV+-.pdf', 'JavaScrip', '', '', '', '', '', '', ''), ('Curriculum actualizado. (2).pdf', 'Python', '', '', '', '', '', '', ''), ('Curriculum actualizado. (2).pdf', 'Java', '', '', '', '', '', '', ''), ('CV ROMINA CAVALLARO.pdf', 'Python', '', '', 'SQL', '', '', '', ''), ('CV ROMINA CAVALLARO.pdf', 'Java', '', '', '', '', '', '', ''), ('CV ROMINA CAVALLARO.pdf', 'Html', '', '', '', '', '', '', ''), ('CV ROMINA CAVALLARO.pdf', 'Css', '', '', '', '', '', '', ''), ('CV ROMINA CAVALLARO.pdf', 'JavaScrip', '', '', '', '', '', '', ''), ('CV-ES.pdf', 'Java', 'ODI', '', '', '', '', '', ''), ('CV-ES.pdf', 'Ruby', '', '', '', '', '', '', ''), ('CV-ES.pdf', 'Html', '', '', '', '', '', '', ''), ('CV-ES.pdf', 'Css', '', '', '', '', '', '', ''), ('CV-ES.pdf', 'JavaScrip', '', '', '', '', '', '', ''), ('CV-Nicolas-Demaria .pdf', 'Python', '', '', 'SQL', 'Tableau', '', '', ''), ('CV_diegoCastells.pdf', 'Python', 'SSIS', 'AWS', 'SQL', 'Metabase', '', '', 'Google BigQuery'), ('CV_diegoCastells.pdf', 'Bash', 'ODI', 'Google Cloud Platform', 'PostgreSQL', 'Power BI', '', '', ''), ('CV_diegoCastells.pdf', 'Html', '', 'GCP', '', '', '', '', ''), ('data-engineer-resume-example.pdf', 'Python', '', 'AWS', 'SQL', 'Tableau', '', 'Spark', ''), ('data-engineer-resume-example.pdf', '', '', '', 'MySQL', '', '', '', ''), ('Evaristo Compagnucci (5).pdf', 'Python', '', '', '', '', '', '', ''), ('Evaristo Compagnucci (5).pdf', 'Java', '', '', '', '', '', '', ''), ('Evaristo Compagnucci (5).pdf', 'Ruby', '', '', '', '', '', '', ''), ('Facundo_Lede_CV.pdf', 'Python', 'ODI', '', 'SQL', '', 'NumPy', '', ''), ('Facundo_Lede_CV.pdf', 'Java', '', '', '', '', 'Pandas', '', ''), ('Facundo_Lede_CV.pdf', 'Bash', '', '', '', '', '', '', ''), ('Facundo_Lede_CV.pdf', 'Html', '', '', '', '', '', '', ''), ('Francisco Heras_CV.pdf', 'Python', '', '', '', '', '', '', ''), ('Francisco Heras_CV.pdf', 'Java', '', '', '', '', '', '', ''), ('Francisco Heras_CV.pdf', 'Html', '', '', '', '', '', '', ''), ("Pedro's Resume (2).pdf", 'Python', '', '', 'SQL', '', '', '', ''), ("Pedro's Resume (2).pdf", 'Java', '', '', '', '', '', '', ''), ("Pedro's Resume (2).pdf", 'Ruby', '', '', '', '', '', '', ''), ('Segovia,Maite-cv.pdf', 'Python', '', '', '', '', '', '', ''), ('Segovia,Maite-cv.pdf', 'Java', '', '', '', '', '', '', ''), ('Segovia,Maite-cv.pdf', 'Ruby', '', '', '', '', '', '', ''), ('Segovia,Maite-cv.pdf', 'Html', '', '', '', '', '', '', '')]
Archivo CSV guardado exitosamente como 'C:/Users/Usuario/Desktop/PP/CV-automatization/2.cv_proccesed/data.csv'

In [28]:
path = "C:/Users/Usuario/Desktop/PP/CV-automatization/2.cv_proccesed/data.csv"
data = pd.read_csv(path,encoding="utf-8")
data.head(10)

,Nombre,Lenguajes,ETL,Cloud,Clientes_base_datos,Visualizacion,Data_Science,Big_Data,Almacenes_de_datos
0,1651669707651.pdf,Java,DataStage,NaN,SQL,NaN,NaN,NaN,NaN
1,1651669707651.pdf,Html,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1651669707651.pdf,Css,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1651669707651.pdf,JavaScrip,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1658588734591.pdf,NaN,SSIS,NaN,SQL,Power BI,NaN,NaN,NaN
5,1658588734591.pdf,NaN,ODI,NaN,NaN,NaN,NaN,NaN,NaN
6,1658847017582.pdf,Python,NaN,AWS,SQL,NaN,Pandas,Spark,NaN
7,1658847017582.pdf,Scala,NaN,GCP,MySQL,NaN,NaN,NaN,NaN
8,1658847017582.pdf,Sas,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1660228502343.pdf,Python,NaN,Amazon Web Services,SQL,Power BI,NumPy,NaN,NaN

In [29]:
# Normalizar la columna "Cloud"
data['Cloud'] = data['Cloud'].replace('Amazon Web Services', 'AWS')
data['Cloud'] = data['Cloud'].replace('Google Cloud Platform', 'GCP')
path_cand = "C:/Users/Usuario/Desktop/PP/CV-automatization/2.cv_proccesed/Candidatos.csv"
data.to_csv(path_cand, index=False)
#data.head(1000)